paginate: 5
paginate_path: "/blog/pages/:num/"
permalink: /blog/posts/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"